# -*- coding: utf-8 -*-
"""Morse para LN.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dR9jAt79XRdwPVFUf5fFpflwGqpyc2OV
"""

morse = input('Código: ')

palavras = morse.split(" / ")

caracteres_morse = {'.-': 'A', '-...': 'B', '-.-.': 'C', '-..': 'D', '.': 'E', '..-.': 'F', '--.': 'G', '....': 'H', '..': 'I', '.---': 'J', '-.-': 'K', '.-..': 'L', '--': 'M', '-.': 'N', '---': 'O', '.--.': 'P', '--.-': 'Q', '.-.': 'R', '...': 'S', '-': 'T', '..-': 'U', '...-': 'V', '.--': 'W', '-..-': 'X', '-.--': 'Y', '--..': 'Z'}

def MorseToLn(palavra):
  caracteres = palavra.split(" ")
  auxiliar = []
  for c in caracteres:
    auxiliar.append(caracteres_morse[c])
  return ''.join(auxiliar)
for palavra in palavras:
  print(MorseToLn(palavra), end=' ')